### ISSUE TITLE
Clean up branches and enable auto-deleting of p/r branches

### ISSUE THREAD

**Issue by werediver** [chifir/UnixStamp#7]
To keep the repository uncluttered, I'd recommend enabling automatic deletion of pull-request branches.

![telegram-cloud-photo-size-2-5474625599545926773-x](https://github.com/user-attachments/assets/eaef44df-d302-4792-9c0c-5d80be04c41c)

And, maybe delete the old existing branches too.

**Comment by chifir** [comment]
Thank you for highlighting that! 
![image](https://github.com/user-attachments/assets/959f04f1-3426-467f-bf05-0e9bdc234d9b)
